In [1]:
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df=pd.read_csv('indiancrop_dataset.csv')
df.head(10)

N_SOIL  P_SOIL  K_SOIL  TEMPERATURE   HUMIDITY        ph    RAINFALL  \
0      90      42      43    20.879744  82.002744  6.502985  202.935536   
1      85      58      41    21.770462  80.319644  7.038096  226.655537   
2      60      55      44    23.004459  82.320763  7.840207  263.964248   
3      74      35      40    26.491096  80.158363  6.980401  242.864034   
4      78      42      42    20.130175  81.604873  7.628473  262.717340   
5      69      37      42    23.058049  83.370118  7.073454  251.055000   
6      69      55      38    22.708838  82.639414  5.700806  271.324860   
7      94      53      40    20.277744  82.894086  5.718627  241.974195   
8      89      54      38    24.515881  83.535216  6.685346  230.446236   
9      68      58      38    23.223974  83.033227  6.336254  221.209196   

                 STATE  CROP_PRICE  CROP  
0  Andaman and Nicobar        7000  Rice  
1  Andaman and Nicobar        5000  Rice  
2  Andaman and Nicobar        7000  Rice  
3  Andaman and Nicobar        7000  Rice  
4  Andaman and Nicobar      120000  Rice  
5  Andaman and Nicobar        3500  Rice  
6  Andaman and Nicobar        7500  Rice  
7  Andaman and Nicobar        6500  Rice  
8  Andaman and Nicobar       10000  Rice  
9  Andaman and Nicobar       11000  Rice

In [3]:
df.info


<bound method DataFrame.info of       N_SOIL  P_SOIL  K_SOIL  TEMPERATURE   HUMIDITY        ph    RAINFALL  \
0         90      42      43    20.879744  82.002744  6.502985  202.935536   
1         85      58      41    21.770462  80.319644  7.038096  226.655537   
2         60      55      44    23.004459  82.320763  7.840207  263.964248   
3         74      35      40    26.491096  80.158363  6.980401  242.864034   
4         78      42      42    20.130175  81.604873  7.628473  262.717340   
...      ...     ...     ...          ...        ...       ...         ...   
2195     107      34      32    26.774637  66.413269  6.780064  177.774507   
2196      99      15      27    27.417112  56.636362  6.086922  127.924610   
2197     118      33      30    24.131797  67.225123  6.362608  173.322839   
2198     117      32      34    26.272418  52.127394  6.758793  127.175293   
2199     104      18      30    23.603016  60.396475  6.779833  140.937041   

                    STATE  CROP

In [4]:
df.describe

<bound method NDFrame.describe of       N_SOIL  P_SOIL  K_SOIL  TEMPERATURE   HUMIDITY        ph    RAINFALL  \
0         90      42      43    20.879744  82.002744  6.502985  202.935536   
1         85      58      41    21.770462  80.319644  7.038096  226.655537   
2         60      55      44    23.004459  82.320763  7.840207  263.964248   
3         74      35      40    26.491096  80.158363  6.980401  242.864034   
4         78      42      42    20.130175  81.604873  7.628473  262.717340   
...      ...     ...     ...          ...        ...       ...         ...   
2195     107      34      32    26.774637  66.413269  6.780064  177.774507   
2196      99      15      27    27.417112  56.636362  6.086922  127.924610   
2197     118      33      30    24.131797  67.225123  6.362608  173.322839   
2198     117      32      34    26.272418  52.127394  6.758793  127.175293   
2199     104      18      30    23.603016  60.396475  6.779833  140.937041   

                    STATE  CR

In [5]:
df.isnull().sum()

N_SOIL         0
P_SOIL         0
K_SOIL         0
TEMPERATURE    0
HUMIDITY       0
ph             0
RAINFALL       0
STATE          0
CROP_PRICE     0
CROP           0
dtype: int64

In [6]:
df.dtypes

N_SOIL           int64
P_SOIL           int64
K_SOIL           int64
TEMPERATURE    float64
HUMIDITY       float64
ph             float64
RAINFALL       float64
STATE           object
CROP_PRICE       int64
CROP            object
dtype: object

In [7]:
from scipy import stats
# removing the outlier
df = df[(np.abs(stats.zscore(df.select_dtypes(include=[np.number]))) < 3).all(axis=1)] 

In [8]:
df.columns

Index(['N_SOIL', 'P_SOIL', 'K_SOIL', 'TEMPERATURE', 'HUMIDITY', 'ph',
       'RAINFALL', 'STATE', 'CROP_PRICE', 'CROP'],
      dtype='object')

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['CROP'] = le.fit_transform(df['CROP'])

C:\Users\arpita\AppData\Local\Temp\ipykernel_21540\3364337810.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CROP'] = le.fit_transform(df['CROP'])


In [10]:
df.dtypes


N_SOIL           int64
P_SOIL           int64
K_SOIL           int64
TEMPERATURE    float64
HUMIDITY       float64
ph             float64
RAINFALL       float64
STATE           object
CROP_PRICE       int64
CROP             int32
dtype: object

In [28]:
# Standardize or normalize
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
from sklearn.preprocessing import StandardScaler
numerical_columns = df.select_dtypes(include=[np.number]).columns.tolist()

# Initialize StandardScaler
scaler = StandardScaler()

# Fit-transform all numerical columns
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

# Display standardized DataFrame
print(df.head(3))

     N_SOIL    P_SOIL    K_SOIL  TEMPERATURE  HUMIDITY        ph  RAINFALL  \
0  1.010885 -0.262841  0.044073    -1.033715  0.498255  0.028768  1.918144   
1  0.877397  0.285116 -0.006371    -0.840938  0.423644  0.778395  2.369044   
2  0.209957  0.182374  0.069296    -0.573865  0.512353  1.902056  3.078254   

                 STATE  CROP_PRICE      CROP  
0  Andaman and Nicobar    2.112194  1.507588  
1  Andaman and Nicobar    1.176925  1.507588  
2  Andaman and Nicobar    2.112194  1.507588  


C:\Users\arpita\AppData\Local\Temp\ipykernel_21540\1748250141.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[numerical_columns] = scaler.fit_transform(df[numerical_columns])


In [29]:
df.duplicated().sum()

0

In [30]:
# frome here our model start traning 
# here i am defining the x and y and target vakues
X = df[['N_SOIL', 'P_SOIL', 'K_SOIL', 'TEMPERATURE', 'HUMIDITY', 'ph', 'RAINFALL']]

y = df['CROP']

In [43]:
# Convert the target variable to categorical if necessary
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
class_names = list(label_encoder.classes_.astype(str))

In [44]:
df.dtypes

N_SOIL         float64
P_SOIL         float64
K_SOIL         float64
TEMPERATURE    float64
HUMIDITY       float64
ph             float64
RAINFALL       float64
STATE           object
CROP_PRICE     float64
CROP           float64
dtype: object

In [45]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [46]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [47]:
from sklearn.ensemble import RandomForestClassifier

# Initialize the classifier
clf = RandomForestClassifier(random_state=42)

# Train the classifier on the training data
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [48]:
y_pred = clf.predict(X_test)

In [49]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9950372208436724


In [50]:
#classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00        21
           4       1.00      1.00      1.00        20
           5       1.00      1.00      1.00        25
           6       1.00      1.00      1.00        15
           7       1.00      1.00      1.00         7
           8       0.83      1.00      0.91        10
           9       1.00      1.00      1.00        25
          10       1.00      1.00      1.00        19
          11       1.00      1.00      1.00        16
          12       1.00      1.00      1.00        15
          13       1.00      1.00      1.00        19
          14       1.00      1.00      1.00        22
          15       1.00      1.00      1.00        25
          16       1.00      1.00      1.00        20
   

In [51]:
# confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Confusion Matrix:
[[14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  

In [52]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [53]:
classifiers = {
    "Logistic Regression": LogisticRegression(max_iter=200),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(random_state=42),
    "Support Vector Machine": SVC(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB()
}

In [54]:
results = {}

for name, clf in classifiers.items():
    # Train the classifier
    clf.fit(X_train, y_train)
    
    # Predict on the test data
    y_pred = clf.predict(X_test)
    
    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    
    # Store the results
    results[name] = {
        "accuracy": accuracy,
        "classification_report": classification_report(y_test, y_pred, target_names=class_names),
        "confusion_matrix": confusion_matrix(y_test, y_pred)
    }

In [56]:
# Print the results
for name, metrics in results.items():
    print(f"Classifier: {name}")
    print(f"Accuracy: {metrics['accuracy']}")
    print("Classification Report:")
    print(metrics['classification_report'])
    print("Confusion Matrix:")
    print(metrics['confusion_matrix'])


Classifier: Logistic Regression
Accuracy: 0.9652605459057072
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           2       0.94      0.89      0.91        18
           3       1.00      1.00      1.00        21
           4       0.95      1.00      0.98        20
           5       1.00      1.00      1.00        25
           6       0.94      1.00      0.97        15
           7       1.00      1.00      1.00         7
           8       0.69      0.90      0.78        10
           9       1.00      1.00      1.00        25
          10       0.86      1.00      0.93        19
          11       1.00      0.94      0.97        16
          12       1.00      1.00      1.00        15
          13       1.00      0.89      0.94        19
          14       1.00      1.00      1.00        22
          15       1.00      1.00      1.00        